### ISSUE TITLE
Tagged release?

### ISSUE THREAD

**Issue by exptom** [Edsby/Trumbowyg-Table-Editor#1]
Thank you @timonorawski  for making this awesome plugin.
Is it possible for you to tag a v1.0.0 release and list it in the Bower repository?
It would make it easier for us to incorporate into our project.

**Comment by timonorawski** [comment]
Thanks for using it!

I have tagged a release and registered it with bower, it may take a little time to fully propagate into the registry.

**Comment by exptom** [comment]
Thank you so much for your speedy response, it is working great :+1:
